# Generated by Django 3.1 on 2021-02-15 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customer_usr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='usr',
            new_name='user',
        ),
    ]
